language: java

sudo: required

jdk:
 - oraclejdk8
 
install: true 

#Init a virtual framebuffer for JavaFX
before_script:
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  
script:
  #Sigh. Download latest JDK, because Travis is out of date.
  - sudo apt-get update && sudo apt-get install oracle-java8-installer 
  - java -version
  - gradle test